---
development:
  UNSPLASH_ACCESS_KEY: <UNSPLASH_ACCESS_KEY>
  UNSPLASH_SECRET_KEY: <UNSPLASH_SECRET_KEY>
  GOOGLE_CREDS: '<GOOGLE_CREDS>'
  SESSION_SECRET: <SESSION_SECRET>
  REDISCLOUD_URL: <REDISCLOUD_URL>
test:
  UNSPLASH_ACCESS_KEY: <UNSPLASH_ACCESS_KEY>
  UNSPLASH_SECRET_KEY: <UNSPLASH_SECRET_KEY>
  GOOGLE_CREDS: '<GOOGLE_CREDS>'
  SESSION_SECRET: <SESSION_SECRET>

production:
  UNSPLASH_ACCESS_KEY: <UNSPLASH_ACCESS_KEY>
  UNSPLASH_SECRET_KEY: <UNSPLASH_SECRET_KEY>
  GOOGLE_CREDS: '<GOOGLE_CREDS>'
  SESSION_SECRET: <SESSION_SECRET>
  REDISCLOUD_URL: <REDISCLOUD_URL>
